CREATE SCHEMA New;
GO

CREATE TABLE New.CostCenters(
    Id BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    ShortName NVARCHAR(10) NOT NULL,
    Name NVARCHAR(50) NOT NULL,
    TrakingId NVARCHAR(100) NOT NULL,
	CreatedBy NVARCHAR(150) NOT NULL,
	CreatedOn DATETIME NOT NULL,
	UpdatedBy NVARCHAR(150) NULL,
	UpdatedOn DATETIME NULL,
	IsActive BIT NOT NULL
)

CREATE TABLE New.VoucherTypes(
    Id BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    ShortName NVARCHAR(10) NOT NULL,
    Name NVARCHAR(50) NOT NULL,
    TrakingId NVARCHAR(100) NOT NULL,
	CreatedBy NVARCHAR(150) NOT NULL,
	CreatedOn DATETIME NOT NULL,
	UpdatedBy NVARCHAR(150) NULL,
	UpdatedOn DATETIME NULL,
	IsActive BIT NOT NULL
)

CREATE TABLE New.Vouchers(
	Id BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	VoucherNo NVARCHAR(30) NOT NULL,
	VoucharDate DATE NOT NULL,
	VoucherTypesId BIGINT NOT NULL,
	CostCentersId BIGINT NOT NULL,
	TotalDebitAmount DECIMAL(18,3) NOT NULL,
	TotalCreditAmount DECIMAL(18,3) NOT NULL,
	Narration NVARCHAR(500) NULL,
	TrakingId NVARCHAR(100) NOT NULL,
	CreatedBy NVARCHAR(150) NOT NULL,
	CreatedOn DATETIME NOT NULL,
	UpdatedBy NVARCHAR(150) NULL,
	UpdatedOn DATETIME NULL,
	IsActive BIT NOT NULL

	FOREIGN KEY(VoucherTypesId) REFERENCES New.VoucherTypes(Id),
	FOREIGN KEY(CostCentersId) REFERENCES New.CostCenters(Id)
)

CREATE TABLE New.VouchersLines(
	Id BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	VouchersId BIGINT NOT NULL,
	GlHeadId BIGINT NOT NULL,
	DebitAmount DECIMAL(18,3) NOT NULL,
	CreditAmount DECIMAL(18,3) NOT NULL,
	Particular NVARCHAR(250) NULL,
	TrakingId NVARCHAR(100) NOT NULL,
	CreatedBy NVARCHAR(150) NOT NULL,
	CreatedOn DATETIME NOT NULL,
	UpdatedBy NVARCHAR(150) NULL,
	UpdatedOn DATETIME NULL,
	IsActive BIT NOT NULL

	FOREIGN KEY(VouchersId) REFERENCES New.Vouchers(Id)
)